[project]
name = 'stacks-multisig'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'ST2XV9R7FNJE9ZZYKSR70453N1YT4QDT67AE6Z2PE.sip-010-trait-ft-standard'
[contracts.mock-token-v3]
path = 'contracts/mock-token-v3.clar'
clarity_version = 3
epoch = 3.1

[contracts.multisig-v3]
path = 'contracts/multisig-v3.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
